### ISSUE TITLE
Add XML docs to public methods

### ISSUE THREAD

**Issue by jchannon** [jchannon/Botwin#44]
- [x] BindExtensions - done via #46 
- [x] ValidationExtensions - done via #47 
- [x] QueryStringExtensions - done via #47
- [x] RouteDataExtensions - done via #49 
- [x] StreamExtensions - done via #48
- [x] ResponseExtensions - done via #49 
- [x] BotwinExtensions - done via #50 
- [x] BotwinModule - done via #55 
- [x] BotwinOptions - done via #56 
- [x] IValidatorLocator - done via #57 
- [x] IStatusCodeHandler - done via #58 
- [x] IResponseNegotiator - done via #49
